interface RoleToleranceRule {
  roleId: string;
  xpPenalty: number;
  timeoutMinutes: number;
  deleteMessage: boolean;
  severeXpPenalty?: number;
  severeTimeoutMinutes?: number;
}

export const AUTOMOD_CONFIG = {
  enabled: true,

  moderation: {
    enabled: true,
    model: process.env.OPENAI_MODERATION_MODEL ?? "omni-moderation-latest",

    normalThreshold: 0.65,
    severeThreshold: 0.85,

    xpPenalty: 50,
    severeXpPenalty: 100,

    timeoutMinutes: 10,
    severeTimeoutMinutes: 60,
    rateLimitCooldownMs: 60_000,
    minTextLength: 3,

    categories: [
      "hate",
      "hate/threatening",
      "harassment",
      "harassment/threatening",
      "self-harm",
      "self-harm/intent",
      "self-harm/instructions",
      "sexual",
      "sexual/minors",
      "violence",
      "violence/graphic"
    ]
  },

  deleteMessage: true,

  forbiddenWords: [
    "vai tomar no cu",
    "vai se fuder",
    "vai se foder",
    "seu merda",
    "filha da puta",
    "filho da puta",
    "vai pro inferno",
    "vai pra merda",
    "vtnc",
    "vsf",
    "vai toma no cu",
    "vai se fude",
    "vai se fuder seu merda",
    "vai toma no cu seu lixo",
    "tomar no cu",
    "toma no cu",
    "se fuder",
    "se foder",
    "foda-se voce",
    "foda se voce",
    "fodase voce",
    "vai se lascar",
    "vai se ferrar",
    "seu lixo",
    "seu idiota",
    "sua idiota",
    "seu burro",
    "sua burra",
    "seu imbecil",
    "sua imbecil",
    "seu otario",
    "sua otaria",
    "seu babaca",
    "sua babaca",
    "seu arrombado",
    "sua arrombada",
    "seu nojento",
    "sua nojenta",
    "seu fracassado",
    "sua fracassada",
    "voce e idiota",
    "voce e burro",
    "voce e burra",
    "voce e imbecil",
    "voce e otario",
    "voce e otaria",
    "voce e babaca",
    "voce e nojento",
    "voce e nojenta",
    "voce e inutil",
    "voce e fracassado",
    "voce e fracassada",
    "seu inútil",
    "você é um lixo",
    "você não vale nada",
    "ninguém te quer",
    "ninguém gosta de você",
    "vai se fuder idiota",
    "vai tomar no cu retardado",
    "seu merda inútil",
    "lixo humano",
    "verme",
    "miseravel",
    "desgracado",
    "desgracada",
    "escoria humana",
    "nojo de voce",
    "tenho nojo de voce",
    "tomara que voce morra",
    "vai morrer",
    "se mata",
    "escória",
    "fdp",
    "pqp",
    "krl",
    "tnc",
    "tmnc",
    "vtmnc",
    "sfd",
    "caralho",
    "porra",
    "merda",
    "bosta",
    "cuzao",
    "cuzona",
    "otario",
    "otaria",
    "babaca",
    "imbecil",
    "idiota",
    "arrombado",
    "arrombada",
    "fuder",
    "foder",
    "fuck you",
    "you piece of shit",
    "you are trash",
    "go to hell",
    "shut the fuck up",
    "fuck off",
    "stfu",
    "kys",
    "kill yourself",
    "go kill yourself",
    "piece of shit",
    "motherfucker",
    "asshole",
    "bitch",
    "trash",
    "moron",
    "idiot",
    "you are stupid",
    "you are dumb"
  ],

  ignoredRoleIds: [
    "1104071797244166176",
    "1104060031751688202",
    "1105231846490513509"
  ],

  ignoredUserIds: ["1004162142834012202"],

  roleToleranceRules: [] as RoleToleranceRule[]
};
